name: Update README with Sorted Papers Content

on:
  push:
    paths:
      - 'update_template_or_data/update_paper_list.md'         # 监听 update_paper_list.md 文件的更新
      - 'scripts/sort_by_date.py'   # 监听 scripts/sort_by_date.py 脚本的更新
      - 'update_template_or_data/update_readme_template.md'   # 监听 scripts/sort_by_date.py 脚本的更新
      - '.github/workflows/main.yml'
  # schedule:
  #   - cron: '0 0 * * *'     # 每天定时运行（0点）

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # 使用最新的 Python 版本

      - name: Install dependencies
        run: |
          pip install pandas

      - name: Run scripts/sort_by_date.py
        run: |
          python scripts/sort_by_date.py

      - name: Update temp_readme.md with sorted papers content
        run: |
          # 读取更新后的 update_template_or_data/update_paper_list.md 内容
          CONTENT=$(cat update_template_or_data/update_paper_list.md)
          
          # 使用 sed 插入 content 到 temp_readme.md 的占位符位置
          sed -i '/{{insert_content_here}}/{
            r /dev/stdin
            d
          }' update_template_or_data/update_readme_template.md <<< "$CONTENT"




      - name: Overwrite README.md with updated temp_readme.md
        run: |
          # 覆盖 README.md
          cp update_template_or_data/update_readme_template.md README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md update_template_or_data/update_paper_list.md grouped_papers/env_desktop.md grouped_papers/env_general.md grouped_papers/env_gui.md grouped_papers/env_mobile.md grouped_papers/env_web.md 
          git commit -m "Update README with sorted content from update_template_or_data/update_paper_list.md"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
