name: Update README with Sorted Papers Content

on:
  push:
    paths:
      - 'papers.md'         # 监听 papers.md 文件的更新
      - 'sort_by_date.py'   # 监听 sort_by_date.py 脚本的更新
  schedule:
    - cron: '0 0 * * *'     # 每天定时运行（0点）

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # 使用最新的 Python 版本

      - name: Install dependencies
        run: |
          pip install pandas

      - name: Run sort_by_date.py
        run: |
          python sort_by_date.py

      - name: Update README.md with sorted papers content
        run: |
          # 读取更新后的 papers.md 内容
          CONTENT=$(cat papers.md)
          # 使用 EOF 将 papers.md 的内容插入到 README.md 的占位符位置
          sed -i '/{{insert_content_here}}/{
            r /dev/stdin
            d
          }' README.md <<< "$CONTENT"

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md papers.md
          git commit -m "Update README with sorted content from papers.md"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
